---
name: Run pre-commit hooks

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.x
      - uses: pre-commit/action@v3.0.0
